config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :edit, :create, :update, :show] do
    member do
      get 'verify/:token', action: :verify, as: 'verification_token'
      get 'reset/:token', action: :edit, controller: :password_resets, as: 'reset_token'
      post 'reset/:token', action: :update, controller: :password_resets, as: 'reset_password'
      get 'credit_transactions', action: :index, controller: :credit_transactions
    end
  end

  resources :questions do
    get 'drafts', on: :collection
    resources :comments, only: [:create]
    resources :answers, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
  end

  resources :spams, only: [:create]

  get 'profile', to: 'users#profile'
  get 'notifications', to: 'notifications#index'
  get 'credit_transactions', to: 'credit_transactions#index'
  get 'payment_transactions', to: 'payment_transactions#index'
  resources :votes, only: [:create]
  resources :packs, only: [:index] do
    member do
      get 'payment', to: 'payment_transactions#new'
      post 'payment', to: 'payment_transactions#create'
    end
  end

  get 'topics', action: :search, controller: :topics
  get 'notifications_poll', action: :poll, controller: :notifications
  get 'mark_notification', action: :mark_viewed, controller: :notifications
  get 'password_resets/new'
  post 'password_resets/create'

  namespace :admin do
    root to: 'users#index'
    get 'send_daily_report', to: 'daily_reports#send_report'
    resources :users, only: [:index, :edit, :update, :destroy] do
      get 'credit_transactions', on: :member, to: 'credit_transactions#index'
    end
  end

  namespace :api, constraints: lambda { |req| req.format == :json } do
    resources :questions, only: [:index]
    get 'feed', to: 'questions#feed'
  end

  controller :sessions do
    get 'login', action: :new
    post 'login', action: :create
    delete 'logout', action: :destroy
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.production?
  root action: :index, controller: :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id             :bigint           not null, primary key
#  title          :string           default(""), not null
#  content        :text             default(""), not null
#  user_id        :bigint           not null
#  published_at   :datetime
#  comments_count :bigint           default(0), not null
#  answers_count  :bigint           default(0), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  net_upvotes    :integer          default(0), not null
#  marked_abuse   :boolean          default(FALSE)
#
class Question < ApplicationRecord
  include BasicPresenter::Concern
  include VotableFeatures
  attr_accessor :new_publish
  paginates_per 6

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  with_options if: :published? do
    validates :content, presence: true
    validates :content_words, length: {
      minimum: ENV['minimum_content_length'].to_i,
      message: I18n.t('question.errors.content_length')
    }
    validates :topics, length: {
      minimum: 1,
      message: I18n.t('question.errors.topics_absent')
    }
  end

  belongs_to :user
  has_one_attached :attachment
  has_and_belongs_to_many :topics
  has_many :credit_transactions, as: :creditable
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :restrict_with_error
  has_many :votes, as: :votable, dependent: :restrict_with_error
  has_many :answers, dependent: :restrict_with_error
  has_many :spams, as: :spammable

  with_options if: :new_publish do
    before_validation :set_published_at
    after_commit :notify_users, on: [:create, :update]
  end
  before_create :check_if_user_has_credits
  before_update :check_if_question_is_updatable
  before_save :attachment_mime_type
  after_create_commit :deduct_credit_of_user
  after_destroy_commit :add_credit_back_to_user

  scope :published, -> { where.not(published_at: nil).where(marked_abuse: false) }
  scope :unpublished, -> { where(published_at: nil).or(where(marked_abuse: true)) }
  scope :by_title, ->(title = nil) { where("lower(title) like ?", "%#{title.downcase}%") }

  def self.search_for_ids(term = '')
  find_by_sql ["SELECT id FROM questions WHERE title LIKE :term
    UNION SELECT id FROM questions WHERE id IN(SELECT questions_topics.question_id
    FROM topics JOIN questions_topics ON questions_topics.topic_id = topics.id
    WHERE topics.name LIKE :term)", { term: "%#{term.downcase}%" }]
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def published?
    published_at.present?
  end

  def set_published_at
    self.published_at = Time.current
  end

  def set_topics(topic_names)
    self.topics = Topic.get_topics_by_names(topic_names) unless published?
  end

  def topic_names
    topics.pluck(:name)
  end

  def posted_by?(user_obj)
    user == user_obj
  end

  private def check_if_user_has_credits
    if user.credits < ENV['ask_question_credit'].to_i
      errors.add(:base, I18n.t('question.errors.not_enough_credits'))
      throw :abort
    end
  end

  private def check_if_question_is_updatable
    if votes.count.positive? || answers_count.positive? || comments_count.positive?
      errors.add(:base, I18n.t('question.errors.not_updatable'))
      throw :abort
    end
  end

  private def deduct_credit_of_user
    unless user.credit_transactions.create(
        credits: -1 * ENV['ask_question_credit'].to_i,
        reason: 'question asked',
        creditable: self
      )
      raise 'something went wrong, error code [:credit-deduction-failed]'
    end
  end

  private def add_credit_back_to_user
    unless user.credit_transactions.create(
        credits: ENV['ask_question_credit'].to_i,
        reason: 'deleted question asked',
        creditable: self
      )
      raise 'something went wrong, error code [:credit-addition-failed]'
    end
  end

  private def notify_users
    users_to_notfy = topics.joins(:topics_users).distinct.pluck('topics_users.user_id') - [user.id]
    users_to_notfy.each { |id| notifications.create(user_id: id, message: '.new_question') }
  end

  private def attachment_mime_type
    if attachment.attached? && !(attachment.content_type == 'application/pdf' || attachment.image?)
      errors.add(:attachment, I18n.t('question.errors.invalid_file'))
      throw :abort
    end
  end
end

app/controllers/api/questions_controller.rb
module Api
  class QuestionsController < BaseController
    skip_before_action :rate_limit_api_calls, only: [:feed]
    skip_around_action :save_api_request, only: [:feed]
    skip_before_action :authorize, only: [:index]

    def index
      @questions = Question.published.includes([:user]).order(published_at: :desc).limit(ENV['array_limit_for_json'])
    end

    def feed
      @questions = Question
        .distinct
        .joins(:questions_topics)
        .where(questions_topics: {topic_id: @user.topics})
        .published
        .includes([:user])
        .order(published_at: :desc)
        .limit(ENV['array_limit_for_json'])
      render 'api/questions/index'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :create_comment]
  before_action :set_user_for_question, only: [:index]
  before_action :check_if_user_has_credits, only: [:new, :create]
  before_action :verify_user, only: [:edit, :update, :destroy]

  def index
    @questions = get_questions_for_index.includes([:attachment_attachment, :comments]).page(params[:page])
  end

  def show
  end

  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    @topics = @question.topic_names.join(', ')
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)
    set_question_parameters
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: t(".#{@question.published? ? 'published' : 'saved'}") }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    set_question_parameters
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: t('.updated') }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: t('.destroyed') }
      format.json { head :no_content }
    end
  end

  def drafts
    @questions = current_user.questions.unpublished.page(params[:page])
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_question
    @question = Question.includes([:user, :comments]).find_by_id(params[:id])
    if @question.blank?
      redirect_to root_path, notice: t('.question_not_found')
    end
  end

  # Only allow a list of trusted parameters through.
  private def question_params
    params.require(:question).permit(:attachment, :title, :content)
  end

  private def set_question_parameters
    @topics = params[:question][:topics]
    @question.set_topics @topics
    @question.new_publish = true unless(@question.published? || params[:question][:publish] == '0')
  end

  private def verify_user
    unless @question.posted_by?(current_user)
      redirect_to root_path, notice: t('.access_denied')
    end
  end

  private def check_if_user_has_credits
    if current_user.credits < ENV['ask_question_credit'].to_i
      redirect_to root_path, notice: t('.not_enough_credits')
    end
  end

  private def set_user_for_question
    if params[:user].present? && !(@user = User.find_by_id(params[:user]))
      redirect_to root_path, notice: t('.user_not_found')
    end
  end

  private def get_questions_for_index
    questions = Question.published.includes([:user])
    if params[:search].present?
      @search = params[:search]
      questions = questions.where id: Question.search_for_ids(params[:search])
    elsif params[:topic].present?
      questions = questions.joins(:questions_topics).where(questions_topics: { topic_id: Topic.by_names([params[:topic]]) })
    elsif params[:user].present?
      questions = @user.questions
    end
    questions.distinct.order(published_at: 'desc')
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true, method: method) do |form| %>
  <%= errors_explanation_div(question) %>

  <% content_for :css do %>
    <%= stylesheet_link_tag "//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" %>
  <% end %>

  <div class="form-group">
    <%= form.label :attachment %>
    <%= form.file_field :attachment, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <%= form.label :topics %>
    <%= form.text_field :topics, value: @topics, data: { url: topics_path }, class: 'form-control' %>
    <small id="topicsHelpBlock" class="form-text text-muted"><%=t('.topics_help_block')%></small>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control', rows: '5' %>
    <small class="form-text text-muted"><%=raw t('.markdown_help_block')%></small>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :publish, class: 'form-check-input' %>
    <%= form.label :publish, t('.publish_now'), class: 'form-check-label' %>
  </div>

  <div class="actions">
    <%= form.submit t('.submit'), class: "btn btn-primary"  %>
    <%= link_to "Back", :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="card">
  <h5 class="card-header"><%= link_to question.title, question_path(question) %></h5>
  <div class="card-body">

    <% if question.attachment.attached? %>
      <% if question.attachment.image? %>
        <%= image_tag question.attachment, class: 'question-image' %>
      <% else %>
        <p class="card-title">
          <%= t('.file_attached') %>
          <%= link_to(question.attachment.blob.filename.sanitized, rails_blob_url(question.attachment, disposition: 'attachment')) %>
        </p>
      <% end %>
    <% end %>

    <p class="card-text"><%= question.presenter.render_content %></p><hr/>

    <div class="d-flex">

      <% if question.published? %>
        <div class="col-3"><%= votes_div :question, question %></div>
        <div class="col-6">
          <a data-toggle="collapse" href="#commentsForQuestion<%= question.id %>" class="btn btn-outline-primary">
            Comments (<span id='commentsCountOfQuestion<%= question.id %>'><%= question.comments_count %></span>)
          </a>
          <a href="<%= question_path(question) %>#answerInputForm" class="btn btn-outline-success">Answers (<%= question.answers_count %>)</a>
          <% if current_user.spammed? (question) %>
            <a href="#" class="btn btn-outline-danger disabled" aria-disabled="true">Spam</a>
          <% else %>
            <a href="#" class="btn btn-outline-danger" data-toggle="modal" data-target="#spamModal" data-for="question-<%= question.id %>">Spam</a>
          <% end %>
        </div>
      <% end %>

      <div class="col-3">
        <p class="card-text">
          <% if question.published? %>
            Published: <%= time_ago_in_words(question.published_at) %> ago<br/>
            From: <%= link_to_if !question.posted_by?(current_user), question.user.name, user_path(question.user_id) %> <br/>
          <% end %>
          Topics: <%= topic_links(question) %>
        </p>
      </div>

    </div>
    <div class="collapse" id="commentsForQuestion<%= question.id %>">
      <%= render template: 'comments/index', locals: { commentable: question } if question.published? %>
    </div>
  </div>
</div>

app/views/questions/_search_form.html.erb
<%= form_with url: root_path, local: true, method: :get, class:"form-inline" do |form| %>
  <div class="input-group">
    <div class="collapse" id="searchForm">
      <%= form.text_field :search, value: @search, class: 'form-control', placeholder: t(".search"), required: true%>
      <small id="searchHelp" class="form-text text-muted"><%=t('.help_block')%></small>
    </div>
    <a data-toggle="collapse" href="#searchForm"><%= image_tag 'search.svg', class: "btn btn-outline-light" %></a>
  </div>
<% end %>

app/views/questions/drafts.html.erb
<h1><%= t('.drafts_heading') %></h1>
<% if @questions.blank? %>
  <h2>No Drafts present</h2>
<% else %>
  <%= render @questions %>
  <%= paginate @questions %>
<% end %>

app/views/questions/edit.html.erb
<div class='col-lg-6 offset-lg-1'>
  <h1>Editing Question</h1>
  <hr />
  <%= render 'form', question: @question, method: :put %>
</div>

app/views/questions/index.html.erb
<% if params[:topic].present? %>
  <h2 class="alert alert-dark" role="alert"><%= t('.questions_by_topic') %> '<%= params[:topic] %>'</h2>
<% elsif params[:search].present? %>
  <h2 class="alert alert-dark" role="alert"><%= t('.questions_by_title') %> '<%= params[:search] %>'</h2>
<% elsif params[:user].present? %>
  <h2 class="alert alert-dark" role="alert"><%= t('.questions_by_user') %> '<%= @user ? @user.name : 'Unknown' %>'</h2>
<% end %>

<%= render @questions %>
<%= paginate @questions %>

<% unless @questions.present? %>
  <h1 class="alert alert-dark" role="alert"><%= t('.no_questions') %></h1>
<% end %>

app/views/questions/new.html.erb
<div class='col-lg-6 offset-lg-1'>
  <h1>New Question</h1>
  <hr />
  <%= render 'form', question: @question, method: :post %>
</div>

app/views/questions/show.html.erb
<%= render @question, question: @question %>

<%= link_to 'Back', questions_path, class: 'btn btn-primary' %>
<% if @question.posted_by?(current_user) %>
  <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
  <%= link_to 'Destroy', @question, method: :delete, data: { confirm: t('.confirm_delete') }, class: 'btn btn-danger' %>
<% end %>
<% if @question.published? %>
  <hr/>
  <div class="card border-secondary mb-3" id="answers-container">
    <%= render template: 'answers/index', locals: { question: @question } %>
  </div>
<% end %>