config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :edit, :create, :update, :show] do
    member do
      get 'verify/:token', action: :verify, as: 'verification_token'
      get 'reset/:token', action: :edit, controller: :password_resets, as: 'reset_token'
      post 'reset/:token', action: :update, controller: :password_resets, as: 'reset_password'
      get 'credit_transactions', action: :index, controller: :credit_transactions
    end
  end

  resources :questions do
    get 'drafts', on: :collection
    resources :comments, only: [:create]
    resources :answers, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
  end

  resources :spams, only: [:create]

  get 'profile', to: 'users#profile'
  get 'notifications', to: 'notifications#index'
  get 'credit_transactions', to: 'credit_transactions#index'
  get 'payment_transactions', to: 'payment_transactions#index'
  resources :votes, only: [:create]
  resources :packs, only: [:index] do
    member do
      get 'payment', to: 'payment_transactions#new'
      post 'payment', to: 'payment_transactions#create'
    end
  end

  get 'topics', action: :search, controller: :topics
  get 'notifications_poll', action: :poll, controller: :notifications
  get 'mark_notification', action: :mark_viewed, controller: :notifications
  get 'password_resets/new'
  post 'password_resets/create'

  namespace :admin do
    root to: 'users#index'
    get 'send_daily_report', to: 'daily_reports#send_report'
    resources :users, only: [:index, :edit, :update, :destroy] do
      get 'credit_transactions', on: :member, to: 'credit_transactions#index'
    end
  end

  namespace :api, constraints: lambda { |req| req.format == :json } do
    resources :questions, only: [:index]
    get 'feed', to: 'questions#feed'
  end

  controller :sessions do
    get 'login', action: :new
    post 'login', action: :create
    delete 'logout', action: :destroy
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.production?
  root action: :index, controller: :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :bigint           not null, primary key
#  user_id         :bigint           not null
#  message         :string           default(""), not null
#  viewed          :boolean          default(FALSE), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  notifiable_type :string
#  notifiable_id   :bigint
#
class Notification < ApplicationRecord
  include BasicPresenter::Concern
  paginates_per 10

  belongs_to :user
  belongs_to :notifiable, polymorphic: true

  validates :message, presence: true

  scope :new_notifications, ->{ where(viewed: false) }
  scope :since_time, ->(time) { where('created_at > ?', time) }

  after_commit :set_new_notifications_count_of_user

  private def set_new_notifications_count_of_user
    user.refresh_new_notification_count!
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:mark_viewed]

  def poll
    new_notifications = current_user.notifications.new_notifications
    count = new_notifications.since_time(params[:time]).count
    total = count.zero? ? -1 : new_notifications.count
    render json: { count: count, total: total }
  end

  def index
    @notifications = current_user.notifications.order(created_at: 'desc').page(params[:page])
  end

  def mark_viewed
    if @notification.update(viewed: true)
      render json: { status: true, bellCount: current_user.reload.new_notifications_count }
    else
      render json: { status: false }
    end
  end

  private def set_notification
    unless @notification = current_user.notifications.find_by_id(params[:q])
      render json: { status: false }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<h2><%= t('.index_heading') %></h2>

<div class="row">
  <% if @notifications.blank? %>
    <h2><%= t('.no_notifications') %></h2>
  <% else %>
    <%= content_tag :ul, id: 'notifications-list', class: "list-group", data: { path: mark_notification_path } do %>

      <% @notifications.each do |n| %>
        <%= content_tag :li, class: "list-group-item d-flex justify-content-between #{n.viewed? ? '' : 'list-group-item-primary' }" do %>

          <div class=" justify-content-start">
            <%= n.presenter.display_message %>
            <%= link_to(n.notifiable.title, question_path(n.notifiable)) if n.notifiable.is_a?(Question) %>
          </div>
          <% unless n.viewed? %>
            <div class=" justify-content-end ok-btn">
              <%= link_to 'OK', 'javascript:void(0)', class: "badge badge-info", data: { id: n.id } %>
            </div>
          <% end %>

        <% end %>
      <% end %>

    <% end %>
  <%= paginate @notifications %>
  <% end %>
</div>