config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :edit, :create, :update, :show] do
    member do
      get 'verify/:token', action: :verify, as: 'verification_token'
      get 'reset/:token', action: :edit, controller: :password_resets, as: 'reset_token'
      post 'reset/:token', action: :update, controller: :password_resets, as: 'reset_password'
      get 'credit_transactions', action: :index, controller: :credit_transactions
    end
  end

  resources :questions do
    get 'drafts', on: :collection
    resources :comments, only: [:create]
    resources :answers, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
  end

  resources :spams, only: [:create]

  get 'profile', to: 'users#profile'
  get 'notifications', to: 'notifications#index'
  get 'credit_transactions', to: 'credit_transactions#index'
  get 'payment_transactions', to: 'payment_transactions#index'
  resources :votes, only: [:create]
  resources :packs, only: [:index] do
    member do
      get 'payment', to: 'payment_transactions#new'
      post 'payment', to: 'payment_transactions#create'
    end
  end

  get 'topics', action: :search, controller: :topics
  get 'notifications_poll', action: :poll, controller: :notifications
  get 'mark_notification', action: :mark_viewed, controller: :notifications
  get 'password_resets/new'
  post 'password_resets/create'

  namespace :admin do
    root to: 'users#index'
    get 'send_daily_report', to: 'daily_reports#send_report'
    resources :users, only: [:index, :edit, :update, :destroy] do
      get 'credit_transactions', on: :member, to: 'credit_transactions#index'
    end
  end

  namespace :api, constraints: lambda { |req| req.format == :json } do
    resources :questions, only: [:index]
    get 'feed', to: 'questions#feed'
  end

  controller :sessions do
    get 'login', action: :new
    post 'login', action: :create
    delete 'logout', action: :destroy
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.production?
  root action: :index, controller: :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  name                    :string
#  email                   :string
#  password_digest         :string
#  admin                   :boolean          default(FALSE), not null
#  credits                 :integer          default(0), not null
#  active                  :boolean          default(FALSE), not null
#  confirm_token           :string
#  reset_token             :string
#  reset_sent_at           :datetime
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  new_notifications_count :integer          default(0), not null
#  stripe_token            :string
#  auth_token              :string
#
class User < ApplicationRecord
  paginates_per 5

  has_secure_password
  has_one_attached :avatar
  has_many :credit_transactions, dependent: :restrict_with_error
  has_and_belongs_to_many :topics
  has_many :questions, dependent: :restrict_with_error
  has_many :notifications, dependent: :destroy
  has_many :votes, dependent: :restrict_with_error
  has_many :comments, dependent: :restrict_with_error
  has_many :answers, dependent: :restrict_with_error
  has_many :payment_transactions, dependent: :restrict_with_error
  has_many :spams, dependent: :restrict_with_error

  validates :name, presence: true
  validates :auth_token, uniqueness: true, allow_nil: false, if: :active?
  validates :email, uniqueness: { case_sensitive: false }, format: { with: /\A[\w\d][^@\s]*@[\w\d-]+(\.?[\w]+)*\z/ }
  validates :reset_token, :confirm_token, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :new_notifications_count, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :password, format: {
    with: /\A(?=.{6,})(?=.*[a-zA-Z])(?=.*\d)(?=.*[[:^alnum:]])/x,
    message: I18n.t('user.errors.password_format')
  }, if: :password

  with_options unless: :active?, absence: { message: I18n.t('user.errors.inactive_update') } do
    validates :avatar
    validates :topics
    validates :auth_token
  end

  before_create :set_verification_token, unless: :admin
  after_commit :send_verification_token, unless: :admin, on: [:create]

  scope :active, -> { where active: true }
  scope :without_auth_token, -> { where auth_token: nil }

  def activate(token)
    if token == confirm_token
      self.active = true
      self.confirm_token = nil
      set_auth_token
      assign_signup_credits
      save
    else
      false
    end
  end

  def send_reset_link
    update(reset_token: SecureRandom.urlsafe_base64, reset_sent_at: Time.current)
    UserMailer.delay.reset_password(id)
  end

  def verify_password_reset_token(token)
    (reset_token == token) &&
      (reset_sent_at > ENV['reset_token_valid_hours'].to_i.hours.ago)
  end

  def set_topics(topic_names)
    self.topics = Topic.get_topics_by_names(topic_names)
  end

  def set_auth_token
    self.auth_token = SecureRandom.urlsafe_base64
  end

  def topic_names
    topics.pluck(:name)
  end

  def spammed?(spammable)
    spams.for_spammable(spammable).present?
  end

  def refresh_new_notification_count!
    update_columns(new_notifications_count: notifications.new_notifications.count)
  end

  def create_pending_payment_transaction(pack)
    payment_transactions.pending.create(
      credits: pack.credits,
      amount: pack.current_price,
      purchase_pack: pack
    )
  end

  def create_credit_transaction(pack)
    credit_transactions.create(
      credits: pack.credits,
      reason: pack.name,
      creditable: pack
    )
  end

  def create_refund_credit_transaction(pack, reason ='Asked for refund.')
    credit_transactions.create(
      credits: -1 * pack.credits,
      reason: reason,
      creditable: pack
    )
  end

  def ensure_stripe_customer_exists
    logger.tagged("payment_transaction: customer") do
      unless stripe_token?
        customer_data = {
          email: email,
          name: Rails.env + ' - ' + name,
          address: {city: '', country: '', line1: '', line2: "", postal_code: '', state: ''}
        }
        logger.info("creating new customer with data: #{customer_data}")
        customer = Stripe::Customer.create(customer_data)
        update(stripe_token: customer.id)
      end
    end
  end

  private
    def set_verification_token
      self.confirm_token = SecureRandom.urlsafe_base64
    end

    def send_verification_token
      UserMailer.delay.verification(id)
    end

    def assign_signup_credits
      pack = PurchasePack.default.find_by_name('Sign-Up-Pack')
      payment_transactions.paid.create(
        credits: pack.credits,
        amount: pack.current_price,
        purchase_pack: pack
      )
      create_credit_transaction(pack)
    end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, :check_if_updating_self, only: [:edit, :update, :destroy]

    def index
      @users = User.all.page(params[:page])
    end

    def edit
      @topics = @user.topic_names.join(', ')
    end

    def update
      @user.set_topics params[:user][:topics]
      @user.admin = params[:user][:admin].present?
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_users_path, notice: 'User Successfully Updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      respond_to do |format|
        if @user.destroy
          format.html { redirect_to admin_users_url, notice: t('.destroyed') }
          format.json { head :no_content }
        else
          format.html { redirect_to admin_users_path(@admin), notice: t('.not_destroyed') }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    private def set_user
      unless @user = User.find_by_id(params[:id])
        redirect_to admin_users_path, notice: 'User not found!'
      end
    end

    private def check_if_updating_self
      if current_user == @user
        redirect_to admin_users_path, notice: 'You are trying to update this account!'
      end
    end
    private def user_params
      params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :set_user_to_verify, :ensure_not_logged_in, only: [:verify]
  skip_before_action :authorize, only: [:new, :create, :verify]
  before_action :check_if_already_activated, only: [:verify]

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @topics = current_user.topic_names.join(', ')
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: t('.signed_up') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    current_user.set_topics params[:user][:topics]
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to profile_path, notice: t('.updated') }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def verify
    if @user.activate(params[:token])
      redirect_to login_path, notice: t('.activated', name: @user.name)
    else
      redirect_to login_path, notice: t('.cannot_activate')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id(params[:id])
      if @user.blank?
        redirect_to root_path, notice: t('.not_found')
      end
    end

    def set_user_to_verify
      @user = User.find_by_id(params[:id])
      if @user.blank?
        redirect_to login_path, notice: t('.not_found')
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
    end

    def check_if_already_activated
      if @user.active?
        redirect_to login_path, notice: t('.already_active')
      end
    end

    def ensure_not_logged_in
      if session[:user_id].present?
        redirect_to root_path, notice: t('.logged_in')
      end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, method: method) do |form| %>
  <%= errors_explanation_div(user) %>

  <% if user.active? %>
    <% content_for :css do %>
      <%= stylesheet_link_tag "//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" %>
    <% end %>
    <div class="form-group">
      <%= form.label :avatar %>
      <%= form.file_field :avatar, class: 'form-control-sm' %>
    </div>
    <div class="form-group">
      <%= form.label :topics %>
      <%= form.text_field :topics, value: @topics, data: { url: topics_path }, class: 'form-control' %>
      <small id="topicsHelpBlock" class="form-text text-muted"><%=t('.topics_help_block')%></small>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation, 'Password Confirmation' %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "#{user.active? ? 'Update' : 'Sign Up'}", class: "btn btn-primary btn"  %>
    <%= link_to "Back", :back, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-md-4">
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar, alt: "avatar", class:"mr-1 img-thumbnail profile-pic" %>
    <% else %>
      <%= image_tag 'no_pic.png', class:"mr-1 img-thumbnail profile-pic" %>
    <% end %>
  </div>
  <div class="col-md-8">
    <p>
      <strong>Name:</strong>
      <%= user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= user.email %>
    </p>

    <p>
      <strong>Credits:</strong>
      <%= link_to user.credits, credit_transactions_path %>
    </p>

    <p>
      <strong>Topics:</strong>
      <%= topic_links(user) %>
    </p>

    <% if user == current_user %>
      <p>
        <strong>Auth Token:</strong>
        <%= current_user.auth_token %>
      </p>
    <% end %>
  </div>
</div>

<%= link_to t('.questions'), root_path(user: user.id), class: 'btn btn-outline-primary' %>

app/views/users/edit.html.erb
<div class='col-lg-6 offset-lg-1'>
  <h1><%=t('.edit_heading')%></h1>
  <hr />
  <%= render 'form', user: current_user, method: :put %>
</div>

app/views/users/index.html.erb
<h1><%=t('.index_heading')%></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Credits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.credits %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class='col-lg-6 offset-lg-1'>
  <h1><%= t('.new_user_heading') %></h1>
  <hr />
  <%= render 'form', user: @user, method: :post %>
</div>

app/views/users/profile.html.erb
<%= render current_user, user: current_user %>

<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <%= link_to t('.edit'), edit_user_path(current_user), class: 'btn btn-primary' %>
</div>

app/views/users/show.html.erb
<%= render @user, user: @user %>

<hr/>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <%= link_to "Back", :back, class: 'btn btn-secondary'%>
</div>