config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :edit, :create, :update, :show] do
    member do
      get 'verify/:token', action: :verify, as: 'verification_token'
      get 'reset/:token', action: :edit, controller: :password_resets, as: 'reset_token'
      post 'reset/:token', action: :update, controller: :password_resets, as: 'reset_password'
      get 'credit_transactions', action: :index, controller: :credit_transactions
    end
  end

  resources :questions do
    get 'drafts', on: :collection
    resources :comments, only: [:create]
    resources :answers, only: [:create]
  end

  resources :answers do
    resources :comments, only: [:create]
  end

  resources :spams, only: [:create]

  get 'profile', to: 'users#profile'
  get 'notifications', to: 'notifications#index'
  get 'credit_transactions', to: 'credit_transactions#index'
  get 'payment_transactions', to: 'payment_transactions#index'
  resources :votes, only: [:create]
  resources :packs, only: [:index] do
    member do
      get 'payment', to: 'payment_transactions#new'
      post 'payment', to: 'payment_transactions#create'
    end
  end

  get 'topics', action: :search, controller: :topics
  get 'notifications_poll', action: :poll, controller: :notifications
  get 'mark_notification', action: :mark_viewed, controller: :notifications
  get 'password_resets/new'
  post 'password_resets/create'

  namespace :admin do
    root to: 'users#index'
    get 'send_daily_report', to: 'daily_reports#send_report'
    resources :users, only: [:index, :edit, :update, :destroy] do
      get 'credit_transactions', on: :member, to: 'credit_transactions#index'
    end
  end

  namespace :api, constraints: lambda { |req| req.format == :json } do
    resources :questions, only: [:index]
    get 'feed', to: 'questions#feed'
  end

  controller :sessions do
    get 'login', action: :new
    post 'login', action: :create
    delete 'logout', action: :destroy
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.production?
  root action: :index, controller: :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_navigation.html.erb
<nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><%= image_tag 'logo.svg', alt: 'prashna-logo' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to  "Users", admin_users_path, class: 'nav-link btn btn-outline-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to  "Profile", profile_path, class: 'nav-link btn btn-outline-dark' %>
      </li>
      <li class="nav-item">
        <%= link_to  "Send Report", admin_send_daily_report_path, class: 'nav-link btn btn-outline-dark' %>
      </li>
      <li class="nav-item">
        <div class="dropdown">
          <button class="nav-link btn btn-outline-dark dropdown-toggle" type="button" id="navQuestionMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Question
          </button>
          <div class="dropdown-menu" aria-labelledby="navQuestionMenu">
            <%= link_to "Ask new?", new_question_path, class: 'dropdown-item' %>
            <%= link_to 'Drafts', drafts_questions_path, class: 'dropdown-item' %>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <%= button_to  notifications_path, class: 'btn', method: :get do %>
          <%= image_tag('bell.svg', alt: 'notification-bell') %>
          <%= content_tag :span, current_user.new_notifications_count, class: "badge badge-light", id: "notification-bell-count" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  "logout", logout_path, method: :delete, class: 'nav-link btn btn-outline-dark' %>
      </li>
    </ul>
  </div>
  <%= render "questions/search_form" if current_user %>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><%= image_tag 'logo.svg', alt: 'prashna-logo' %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to  "Profile", profile_path, class: 'nav-link btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <div class="dropdown">
            <button class="nav-link btn btn-outline-dark dropdown-toggle" type="button" id="navQuestionMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Question
            </button>
            <div class="dropdown-menu" aria-labelledby="navQuestionMenu">
              <%= link_to "Ask new?", new_question_path, class: 'dropdown-item' %>
              <%= link_to 'Drafts', drafts_questions_path, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
        <li class="nav-item">
        
        <div class="dropdown">
            <button class="nav-link btn btn-outline-dark dropdown-toggle" type="button" id="navPacksMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Buy Credits
            </button>
            <div class="dropdown-menu" aria-labelledby="navPacksMenu">
              <%= link_to "Packs", packs_path, class: 'dropdown-item' %>
              <%= link_to 'Transactions', payment_transactions_path, class: 'dropdown-item' %>
            </div>
          </div>
        
        </li>
        <li class="nav-item">
          <%= button_to  notifications_path, class: 'btn', method: :get do %>
            <%= image_tag('bell.svg', alt: 'notification-bell') %>
            <%= content_tag :span, current_user.new_notifications_count, class: "badge badge-light", id: "notification-bell-count" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to  "Logout", logout_path, method: :delete, class: 'nav-link btn btn-outline-dark' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to  "Login", login_path, class: 'nav-link btn btn-outline-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to  "Sign-up", new_user_path, class: 'nav-link btn btn-outline-dark' %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= render "questions/search_form" if current_user %>
</nav>

app/views/layouts/_notification.html.erb
<% if current_user.present? %>
  <div aria-live="polite" role="status" aria-atomic="true" style="position: relative;">
  <div class="toast sticky-top" style="position: absolute; top: 0; right: 0;" data-autohide="false" data-path="<%= notifications_poll_path %>" data-notifications_path="<%= notifications_path %>">

    <div class="toast-header">
      <strong class="mr-auto"></strong>
      <small></small>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body"></div>

  </div>
  </div>
<% end %>

<div id='spinnerNotifier'>
  <h3 class="text-danger">
    <span class="spinner-grow mr-2" role="status"></span>
    <em><%= t('.processing') %></em>
  </h3>
</div>

app/views/layouts/_spam_modal.html.erb
<div class="modal fade" id="spamModal" tabindex="-1" role="dialog" aria-labelledby="spamModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t('.title') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_with model: Spam.new, id: 'spamForm' do |f| %>
        <div class="modal-body">
          <%= f.text_area :reason, placeholder: 'Reason..', class: 'form-control' %>
          <div class='spam-successful-message' style='background-color: lightgreen;'></div>
          <div class='spam-unsuccessful-message'  style='background-color: orange;'></div>
        </div>
        <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Submit", class: 'btn btn-primary' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quora Admin" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= content_for :css %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Quora-clone(Prashna)" %>">
  </head>

  <body>

    <header class="main">
      <%= render 'layouts/admin_navigation' %>
      <%= render 'layouts/notification' %>
    </header>
    <section class="content">
      
      <main class='<%= controller.controller_name %>'>
        <% if notice %>
          <aside id="notice"><%= notice %></aside>
        <% end %>
        
        <div class="container"><%= yield %></div>
        
      </main>
    </section>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quora" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= content_for :css %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Quora-clone(Prashna)" %>">
  </head>

  <body>

    <header class="main">
      <%= render 'layouts/navigation' %>
      <% if current_user.present? %>
        <%= render 'layouts/notification' %>
        <%= render 'layouts/spam_modal' %>
      <% end %>
    </header>
    <section class="content">

      <main class='<%= controller.controller_name %>'>
        <% if notice %>
          <aside id="notice"><%= notice %></aside>
        <% end %>

        <div class="container"><%= yield %></div>

      </main>
    </section>

  </body>
</html>